DROP TABLE USERS;
CREATE TABLE USERS(
    ID BIGINT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ROLE VARCHAR(200) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    LOGIN VARCHAR(20) NOT NULL,
    PASSWORDHASH BIGINT NOT NULL);
INSERT INTO USERS VALUES(DEFAULT,
    'ADMIN', 'Administrador', 'admin', 1509442);
INSERT INTO USERS VALUES(DEFAULT,
    'OPERADOR', 'Fulano da Silva', 'fulano', 1509442);

DROP TABLE STUDENTS;
CREATE TABLE STUDENTS(
    ID BIGINT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    PHONE VARCHAR(20) NOT NULL);

DROP TABLE TEACHERS;
CREATE TABLE TEACHERS(
    ID BIGINT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    PHONE VARCHAR(20) NOT NULL);

DROP TABLE CLASSES;
CREATE TABLE CLASSES(
    ID BIGINT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CLASS_NAME VARCHAR(200) NOT NULL,
    PERIOD_CLASS VARCHAR(200) NOT NULL,
    ID_TEACHER BIGINT,
    CONSTRAINT CLASSES_FK FOREIGN KEY (ID_TEACHER) 
        REFERENCES TEACHERS (ID));

DROP TABLE REGISTERS;
CREATE TABLE REGISTERS(
    ID BIGINT NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DATE_REGISTER DATE NOT NULL,
    ID_STUDENT BIGINT,
    ID_CLASS BIGINT,
    CONSTRAINT REGISTER_FK1 FOREIGN KEY (ID_STUDENT) 
        REFERENCES STUDENTS (ID),
    CONSTRAINT REGISTER_FK2 FOREIGN KEY (ID_CLASS) 
        REFERENCES CLASSES (ID));